"""api requests time

Revision ID: 0484a3ab55f4
Revises: 155e9b3ed62b
Create Date: 2019-11-11 00:43:55.767747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0484a3ab55f4'
down_revision = '155e9b3ed62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_request', sa.Column('time', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_request', 'time')
    # ### end Alembic commands ###
