"""api requests

Revision ID: 155e9b3ed62b
Revises: b492aff7ef35
Create Date: 2019-11-11 00:35:37.997213

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '155e9b3ed62b'
down_revision = 'b492aff7ef35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('query')
    )
    op.create_index(op.f('ix_api_request_user_id'), 'api_request', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_api_request_user_id'), table_name='api_request')
    op.drop_table('api_request')
    # ### end Alembic commands ###
