"""empty message

Revision ID: 1769582d6e95
Revises: 0484a3ab55f4
Create Date: 2019-11-11 17:05:51.166985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1769582d6e95'
down_revision = '0484a3ab55f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domainDGA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('family', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_domainDGA_domain'), 'domainDGA', ['domain'], unique=True)
    op.create_index(op.f('ix_domainDGA_family'), 'domainDGA', ['family'], unique=False)
    op.create_table('top_domain',
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=256), nullable=False),
    sa.Column('open_page_rank', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('rank')
    )
    op.create_index(op.f('ix_top_domain_domain'), 'top_domain', ['domain'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_top_domain_domain'), table_name='top_domain')
    op.drop_table('top_domain')
    op.drop_index(op.f('ix_domainDGA_family'), table_name='domainDGA')
    op.drop_index(op.f('ix_domainDGA_domain'), table_name='domainDGA')
    op.drop_table('domainDGA')
    # ### end Alembic commands ###
