"""empty message

Revision ID: 8fcaa5a38cf1
Revises: a24ff4ed4336
Create Date: 2019-11-13 18:55:55.504104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fcaa5a38cf1'
down_revision = 'a24ff4ed4336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_request', sa.Column('token', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_api_request_token'), 'api_request', ['token'], unique=False)
    op.create_foreign_key(None, 'api_request', 'api_token', ['token'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'api_request', type_='foreignkey')
    op.drop_index(op.f('ix_api_request_token'), table_name='api_request')
    op.drop_column('api_request', 'token')
    # ### end Alembic commands ###
