"""empty message

Revision ID: dfb9d3cab77b
Revises: 1769582d6e95
Create Date: 2019-11-11 23:57:31.268667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfb9d3cab77b'
down_revision = '1769582d6e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(length=256), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('page')
    )
    op.create_index(op.f('ix_site_request_user_id'), 'site_request', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_site_request_user_id'), table_name='site_request')
    op.drop_table('site_request')
    # ### end Alembic commands ###
